# Generated by Django 4.2.6 on 2023-11-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(help_text="Name of the forecast period, e.g., 'This Afternoon', 'Tonight'", max_length=100)),
                ('detailed_forecast', models.TextField(help_text='Full text of the weather forecast')),
                ('temperature_high', models.IntegerField(blank=True, help_text='High temperature for the period, if applicable', null=True)),
                ('temperature_low', models.IntegerField(blank=True, help_text='Low temperature for the period, if applicable', null=True)),
                ('wind', models.CharField(blank=True, help_text='Wind conditions for the period', max_length=255)),
                ('chance_of_precipitation', models.IntegerField(blank=True, help_text='Chance of precipitation as a percentage', null=True)),
                ('precipitation_amount', models.CharField(blank=True, help_text='Expected amount of rainfall or precipitation', max_length=255)),
                ('forecast_date', models.DateField(help_text='The date for which the forecast applies')),
            ],
            options={
                'verbose_name': 'Weather Forecast',
                'verbose_name_plural': 'Weather Forecasts',
                'ordering': ['forecast_date', 'period_name'],
            },
        ),
    ]
