# Generated by Django 4.2.6 on 2023-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_weatherforecast_precipitation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='precipitation_amount',
            field=models.CharField(blank=True, default='Not provided', help_text='Expected amount of rainfall or precipitation', max_length=255),
        ),
    ]
