# Generated by Django 4.2.6 on 2023-11-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_alter_weatherforecast_precipitation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='wind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
