# Generated by Django 4.2.6 on 2023-11-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_alter_weatherforecast_wind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='precipitation_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
